[package]
name = "tower-sessions-moka-store"
description = "Moka session store for `tower-sessions`."
version = "0.15.0"
edition = "2021"
authors = ["Max Countryman <hello@maxcountryman.com>"]
license = "MIT"
homepage = "https://github.com/maxcountryman/tower-sessions-stores"
keywords = ["axum", "sessions", "cookie", "tower", "moka"]
categories = ["asynchronous", "network-programming", "web-programming"]
repository = "https://github.com/maxcountryman/tower-sessions-stores"
documentation = "https://docs.rs/tower-sessions-moka-store"
readme = "README.md"

[dependencies]
async-trait = "0.1.92"
moka = { version = "0.12.16", features = ["future"] }
time = "0.3.55"
tower-sessions-core = { version = "0.15.0", git = "https://github.com/sabify/tower-sessions" }

[dev-dependencies]
axum = "0.8.9"
tower-sessions = { version = "0.15.0", git = "https://github.com/sabify/tower-sessions" }
tower-sessions-sqlx-store = { path = "../sqlx-store/", features = ["sqlite"] }
tokio = { version = "1.53.1", features = ["full"] }
tokio-test = "0.4.5"
serde = "1"

[[example]]
name = "moka"
